services:
  - name: spotbulle-backend
    type: web
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn projet_spotbulle:app"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///database.db"
    region: oregon
